### ISSUE TITLE
Add support for S3 compatible services

### ISSUE THREAD

**Issue by iler** [foo-software/lighthouse-check#30]
Would it be possible to add support for other S3 compatible services to upload the reports to? AWS-sdk supports it so it would only require to add support for `endpoint` directive (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Endpoint.html) in to this module :)

**Comment by adamhenson** [comment]
Hi @iler - thanks for opening this. This project uses [lighthouse-persist](https://github.com/foo-software/lighthouse-persist) under the hood. Would you mind opening an issue in that project with the identical description? We'd still need to ensure this project supports it, so we can keep this open for a bit.

To answer your question - yes, although I'm not familiar with the `endpoint` directive, I'd say it is do-able. But, the main change would need to be made in `lighthouse-persist` (which is indeed a [`foo-software`](https://github.com/foo-software) project). I'd invite a PR or wait for other interest and otherwise prioritize it accordingly.
